version: '3.8'

networks:
  dockerapi:
    driver: bridge

services:
  app:
    container_name: app
    image: ittp:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "5000:5000"
    depends_on:
      - database
    networks:
      - dockerapi

  database:
    container_name: database
    image: postgres:latest
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - "./postgresdata:/var/lib/postgresql/data"    
    networks:
      - dockerapi